#!/usr/bin/env bash
# @description: Generates the lab state file (state.env).
#              Sourced by 98_assemble_lab.sh — inherits all variables.
# @generator: generate_state_env.sh
# @author: [Nishchay Dubey/iota-sama]

set -euo pipefail

# -----------------------------------------------------------------------------
# 1. ENVIRONMENT VALIDATION
# -----------------------------------------------------------------------------
: "${LAB_HOME:?LAB_HOME is not set. Run via 98_assemble_lab.sh}"
: "${STACK_ID:?STACK_ID is not set.}"
: "${ENV_NAME:?ENV_NAME is not set.}"

# PostgreSQL variables
: "${PG_VERSION:?PG_VERSION is not set.}"
: "${PGDATA:?PGDATA is not set.}"
: "${PG_BIN_PATH:?PG_BIN_PATH is not set.}"
: "${PG_PORT:?PG_PORT is not set.}"
: "${PG_LAB_USER:?PG_LAB_USER is not set.}"
: "${PG_LAB_DB:?PG_LAB_DB is not set.}"
: "${PG_RUN_DIR:?PG_RUN_DIR is not set.}"
: "${PG_LOG_DIR:?PG_LOG_DIR is not set.}"
: "${PG_CUSTOM_CONF:?PG_CUSTOM_CONF is not set.}"

# Airflow variables
: "${AIRFLOW_PORT:?AIRFLOW_PORT is not set.}"
: "${AIRFLOW_VENV:?AIRFLOW_VENV is not set.}"
: "${AIRFLOW_HOME:?AIRFLOW_HOME is not set.}"
: "${AIRFLOW_CFG:?AIRFLOW_CFG is not set.}"
: "${AIRFLOW_DAGS_FOLDER:?AIRFLOW_DAGS_FOLDER is not set.}"
: "${AIRFLOW_DB_USER:?AIRFLOW_DB_USER is not set.}"
: "${AIRFLOW_DB_NAME:?AIRFLOW_DB_NAME is not set.}"
: "${AIRFLOW_POSTGRES_CONN_ID:?AIRFLOW_POSTGRES_CONN_ID is not set.}"
: "${AIRFLOW_LOG_DIR:?AIRFLOW_LOG_DIR is not set.}"
: "${AIRFLOW_RUN_DIR:?AIRFLOW_RUN_DIR is not set.}"

SECRET_FILE="${LAB_HOME}/secrets/generated.env"
STATE_FILE="${LAB_HOME}/configs/state.env"

# -----------------------------------------------------------------------------
# 2. GENERATE STATE FILE
# -----------------------------------------------------------------------------
cat > "${STATE_FILE}" <<INNEREOF
# ==========================================================
# INTERNAL LAB STATE — Generated by bootstrap-de-stack
# ==========================================================
# DO NOT EDIT THIS FILE.
# This file is regenerated every time the factory runs.
# Use lab_config.sh for custom settings.
# ==========================================================
# Lab Identity
export STACK_ID="${STACK_ID}"
export ENV_NAME="${ENV_NAME}"
export LAB_HOME="${LAB_HOME}"

# PostgreSQL Configuration
export PG_VERSION="${PG_VERSION}"
export PG_PORT="${PG_PORT}"
export PGDATA="${PGDATA}"
export PG_BIN_PATH="${PG_BIN_PATH}"
export PG_RUN_DIR="${PG_RUN_DIR}"
export PG_LOG_DIR="${PG_LOG_DIR}"
export PG_CUSTOM_CONF="${PG_CUSTOM_CONF}"

# Database Access
export PG_LAB_USER="${PG_LAB_USER}"
export PG_LAB_DB="${PG_LAB_DB}"

# Secrets Location
export SECRET_FILE="${SECRET_FILE}"

# Airflow Configuration
export AIRFLOW_PORT="${AIRFLOW_PORT}"
export AIRFLOW_VENV="${AIRFLOW_VENV}"
export AIRFLOW_HOME="${AIRFLOW_HOME}"
export AIRFLOW_CFG="${AIRFLOW_CFG}"
export AIRFLOW_DAGS_FOLDER="${AIRFLOW_DAGS_FOLDER}"
export AIRFLOW_DB_USER="${AIRFLOW_DB_USER}"
export AIRFLOW_DB_NAME="${AIRFLOW_DB_NAME}"
export AIRFLOW_LOG_DIR="${AIRFLOW_LOG_DIR}"
export AIRFLOW_RUN_DIR="${AIRFLOW_RUN_DIR}"
export AIRFLOW_POSTGRES_CONN_ID="${AIRFLOW_POSTGRES_CONN_ID}"
INNEREOF

echo "[INFO] State file generated: ${STATE_FILE}"
