#!/usr/bin/env bash
# @description: Generates the lab shutdown script (lab_shutdown.sh).
#              Sourced by 97_assemble_lab.sh — inherits all variables.
# @generator: generate_lab_shutdown.sh
# @author: [Nishchay Dubey/iota-sama]

set -euo pipefail

# -----------------------------------------------------------------------------
# 1. ENVIRONMENT VALIDATION
# -----------------------------------------------------------------------------
: "${LAB_HOME:?LAB_HOME is not set. Run via 97_assemble_lab.sh}"

SHUTDOWN_SCRIPT="${LAB_HOME}/bin/lab_shutdown.sh"

# -----------------------------------------------------------------------------
# 2. GENERATE LAB SHUTDOWN SCRIPT
# -----------------------------------------------------------------------------
cat > "${SHUTDOWN_SCRIPT}" <<'SHUTEOF'
#!/usr/bin/env bash
set -euo pipefail

# ==========================================================
# LAB SHUTDOWN — Generated by bootstrap-de-stack
# ==========================================================
# Gracefully stops all lab services.
# Usage: bash bin/lab_shutdown.sh
# ==========================================================

LAB_HOME="$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")" 

# Load state
if [[ -f "${LAB_HOME}/configs/state.env" ]]; then
    source "${LAB_HOME}/configs/state.env"
else
    echo "[ERROR] State file not found. Cannot shut down."
    exit 1
fi

echo "[INFO] Shutting down lab: ${ENV_NAME} (${STACK_ID})"

# Stop Airflow API server
if [[ -f "${AIRFLOW_RUNTIME_DIR}/airflow-api-server.pid" ]]; then
    API_PID=$(cat "${AIRFLOW_RUNTIME_DIR}/airflow-api-server.pid")
    if kill -0 "${API_PID}" 2>/dev/null; then
        echo "[INFO] Stopping Airflow API server (PID: ${API_PID})..."
        kill "${API_PID}" 2>/dev/null || true
        TIMEOUT=10
        while kill -0 "${API_PID}" 2>/dev/null && [[ "${TIMEOUT}" -gt 0 ]]; do
            sleep 1
            TIMEOUT=$((TIMEOUT - 1))
        done
        kill -0 "${API_PID}" 2>/dev/null && kill -9 "${API_PID}" 2>/dev/null || true
        rm -f "${AIRFLOW_RUNTIME_DIR}/airflow-api-server.pid"
        echo "[INFO] Airflow API server stopped."
    else
        rm -f "${AIRFLOW_RUNTIME_DIR}/airflow-api-server.pid"
    fi
fi

# Stop Airflow scheduler
if [[ -f "${AIRFLOW_RUNTIME_DIR}/airflow-scheduler.pid" ]]; then
    SCHED_PID=$(cat "${AIRFLOW_RUNTIME_DIR}/airflow-scheduler.pid")
    if kill -0 "${SCHED_PID}" 2>/dev/null; then
        echo "[INFO] Stopping Airflow scheduler (PID: ${SCHED_PID})..."
        kill "${SCHED_PID}" 2>/dev/null || true
        TIMEOUT=10
        while kill -0 "${SCHED_PID}" 2>/dev/null && [[ "${TIMEOUT}" -gt 0 ]]; do
            sleep 1
            TIMEOUT=$((TIMEOUT - 1))
        done
        kill -0 "${SCHED_PID}" 2>/dev/null && kill -9 "${SCHED_PID}" 2>/dev/null || true
        rm -f "${AIRFLOW_RUNTIME_DIR}/airflow-scheduler.pid"
        echo "[INFO] Airflow scheduler stopped."
    else
        rm -f "${AIRFLOW_RUNTIME_DIR}/airflow-scheduler.pid"
    fi
fi

# Stop Kafka Connect
if [[ -n "${CONNECT_RUNTIME_DIR:-}" ]] && [[ -f "${CONNECT_RUNTIME_DIR}/connect.pid" ]]; then
    CONNECT_PID=$(cat "${CONNECT_RUNTIME_DIR}/connect.pid")
    if kill -0 "${CONNECT_PID}" 2>/dev/null; then
        echo "[INFO] Stopping Kafka Connect (PID: ${CONNECT_PID})..."
        kill "${CONNECT_PID}" 2>/dev/null || true
        TIMEOUT=10
        while kill -0 "${CONNECT_PID}" 2>/dev/null && [[ "${TIMEOUT}" -gt 0 ]]; do
            sleep 1
            TIMEOUT=$((TIMEOUT - 1))
        done
        kill -0 "${CONNECT_PID}" 2>/dev/null && kill -9 "${CONNECT_PID}" 2>/dev/null || true
        rm -f "${CONNECT_RUNTIME_DIR}/connect.pid"
        echo "[INFO] Kafka Connect stopped."
    else
        rm -f "${CONNECT_RUNTIME_DIR}/connect.pid"
    fi
fi

# Stop Schema Registry
if [[ -n "${SCHEMA_REGISTRY_RUNTIME_DIR:-}" ]] && [[ -f "${SCHEMA_REGISTRY_RUNTIME_DIR}/schema-registry.pid" ]]; then
    SR_PID=$(cat "${SCHEMA_REGISTRY_RUNTIME_DIR}/schema-registry.pid")
    if kill -0 "${SR_PID}" 2>/dev/null; then
        echo "[INFO] Stopping Schema Registry (PID: ${SR_PID})..."
        kill "${SR_PID}" 2>/dev/null || true
        TIMEOUT=10
        while kill -0 "${SR_PID}" 2>/dev/null && [[ "${TIMEOUT}" -gt 0 ]]; do
            sleep 1
            TIMEOUT=$((TIMEOUT - 1))
        done
        kill -0 "${SR_PID}" 2>/dev/null && kill -9 "${SR_PID}" 2>/dev/null || true
        rm -f "${SCHEMA_REGISTRY_RUNTIME_DIR}/schema-registry.pid"
        echo "[INFO] Schema Registry stopped."
    else
        rm -f "${SCHEMA_REGISTRY_RUNTIME_DIR}/schema-registry.pid"
    fi
fi

# Stop Kafka broker
if [[ -n "${KAFKA_RUNTIME_DIR:-}" ]] && [[ -f "${KAFKA_RUNTIME_DIR}/kafka.pid" ]]; then
    KAFKA_PID=$(cat "${KAFKA_RUNTIME_DIR}/kafka.pid")
    if kill -0 "${KAFKA_PID}" 2>/dev/null; then
        echo "[INFO] Stopping Kafka broker (PID: ${KAFKA_PID})..."
        if command -v "${KAFKA_BIN_PATH}/kafka-server-stop.sh" &>/dev/null; then
            "${KAFKA_BIN_PATH}/kafka-server-stop.sh" 2>/dev/null || true
            TIMEOUT=10
            while kill -0 "${KAFKA_PID}" 2>/dev/null && [[ "${TIMEOUT}" -gt 0 ]]; do
                sleep 1
                TIMEOUT=$((TIMEOUT - 1))
            done
        fi
        kill -0 "${KAFKA_PID}" 2>/dev/null && kill "${KAFKA_PID}" 2>/dev/null || true
        TIMEOUT=5
        while kill -0 "${KAFKA_PID}" 2>/dev/null && [[ "${TIMEOUT}" -gt 0 ]]; do
            sleep 1
            TIMEOUT=$((TIMEOUT - 1))
        done
        kill -0 "${KAFKA_PID}" 2>/dev/null && kill -9 "${KAFKA_PID}" 2>/dev/null || true
        rm -f "${KAFKA_RUNTIME_DIR}/kafka.pid"
        echo "[INFO] Kafka broker stopped."
    else
        rm -f "${KAFKA_RUNTIME_DIR}/kafka.pid"
    fi
fi

# WAL replication slot health check (informational — slot NOT dropped)
if [[ -n "${PG_BIN_PATH:-}" ]] && [[ -n "${PG_RUNTIME_DIR:-}" ]] && [[ -n "${PG_PORT:-}" ]] && [[ -n "${PG_LAB_DB:-}" ]]; then
    if "${PG_BIN_PATH}/pg_isready" -p "${PG_PORT}" -h localhost >/dev/null 2>&1; then
        echo "[INFO] Replication slot status:"
        "${PG_BIN_PATH}/psql" -h "${PG_RUNTIME_DIR}" -p "${PG_PORT}" -d "${PG_LAB_DB}" -t \
            -c "SELECT slot_name, pg_size_pretty(pg_wal_lsn_diff(pg_current_wal_lsn(), restart_lsn)) AS wal_retained, active FROM pg_replication_slots WHERE slot_name LIKE 'debezium_%';" \
            2>/dev/null || true
    fi
fi

# Stop PostgreSQL
if "${PG_BIN_PATH}/pg_isready" -p "${PG_PORT}" -h localhost >/dev/null 2>&1; then
    echo "[INFO] Stopping PostgreSQL on port ${PG_PORT}..."
    "${PG_BIN_PATH}/pg_ctl" -D "${PGDATA}" stop -m fast
    echo "[INFO] PostgreSQL stopped."
else
    echo "[INFO] PostgreSQL is not running."
fi

echo "[SUCCESS] Lab shutdown complete. All services stopped."
SHUTEOF

chmod +x "${SHUTDOWN_SCRIPT}"
echo "[INFO] Shutdown script generated: ${SHUTDOWN_SCRIPT}"