#!/usr/bin/env bash
# @description: Generates the lab shutdown script (lab_shutdown.sh).
#              Sourced by 98_assemble_lab.sh — inherits all variables.
# @generator: generate_lab_shutdown.sh
# @author: [Nishchay Dubey/iota-sama]

set -euo pipefail

# -----------------------------------------------------------------------------
# 1. ENVIRONMENT VALIDATION
# -----------------------------------------------------------------------------
: "${LAB_HOME:?LAB_HOME is not set. Run via 98_assemble_lab.sh}"
: "${PG_PORT:?PG_PORT is not set.}"
: "${PGDATA:?PGDATA is not set.}"
: "${PG_BIN_PATH:?PG_BIN_PATH is not set.}"

SHUTDOWN_SCRIPT="${LAB_HOME}/bin/lab_shutdown.sh"

# -----------------------------------------------------------------------------
# 2. GENERATE LAB SHUTDOWN SCRIPT
# -----------------------------------------------------------------------------
cat > "${SHUTDOWN_SCRIPT}" <<'SHUTEOF'
#!/usr/bin/env bash
set -euo pipefail

# ==========================================================
# LAB SHUTDOWN — Generated by bootstrap-de-stack
# ==========================================================
# Gracefully stops all lab services (Airflow + PostgreSQL).
# Usage: bash bin/lab_shutdown.sh
# ==========================================================

LAB_HOME="$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")" 

# Load state
if [[ -f "${LAB_HOME}/configs/state.env" ]]; then
    source "${LAB_HOME}/configs/state.env"
else
    echo "[ERROR] State file not found. Cannot shut down."
    exit 1
fi

echo "[INFO] Shutting down lab: ${ENV_NAME} (${STACK_ID})"

# Stop Airflow API server
if [[ -f "${AIRFLOW_RUN_DIR}/airflow-api-server.pid" ]]; then
    API_PID=$(cat "${AIRFLOW_RUN_DIR}/airflow-api-server.pid")
    if kill -0 "${API_PID}" 2>/dev/null; then
        echo "[INFO] Stopping Airflow API server (PID: ${API_PID})..."
        kill "${API_PID}" 2>/dev/null || true
        TIMEOUT=10
        while kill -0 "${API_PID}" 2>/dev/null && [[ "${TIMEOUT}" -gt 0 ]]; do
            sleep 1
            TIMEOUT=$((TIMEOUT - 1))
        done
        if kill -0 "${API_PID}" 2>/dev/null; then
            echo "[WARN] Force stopping API server..."
            kill -9 "${API_PID}" 2>/dev/null || true
        fi
        rm -f "${AIRFLOW_RUN_DIR}/airflow-api-server.pid"
        echo "[INFO] Airflow API server stopped."
    else
        rm -f "${AIRFLOW_RUN_DIR}/airflow-api-server.pid"
    fi
fi

# Stop Airflow scheduler
if [[ -f "${AIRFLOW_RUN_DIR}/airflow-scheduler.pid" ]]; then
    SCHED_PID=$(cat "${AIRFLOW_RUN_DIR}/airflow-scheduler.pid")
    if kill -0 "${SCHED_PID}" 2>/dev/null; then
        echo "[INFO] Stopping Airflow scheduler (PID: ${SCHED_PID})..."
        kill "${SCHED_PID}" 2>/dev/null || true
        TIMEOUT=10
        while kill -0 "${SCHED_PID}" 2>/dev/null && [[ "${TIMEOUT}" -gt 0 ]]; do
            sleep 1
            TIMEOUT=$((TIMEOUT - 1))
        done
        if kill -0 "${SCHED_PID}" 2>/dev/null; then
            echo "[WARN] Force stopping scheduler..."
            kill -9 "${SCHED_PID}" 2>/dev/null || true
        fi
        rm -f "${AIRFLOW_RUN_DIR}/airflow-scheduler.pid"
        echo "[INFO] Airflow scheduler stopped."
    else
        rm -f "${AIRFLOW_RUN_DIR}/airflow-scheduler.pid"
    fi
fi

# Stop PostgreSQL
if "${PG_BIN_PATH}/pg_isready" -p "${PG_PORT}" -h localhost >/dev/null 2>&1; then
    echo "[INFO] Stopping PostgreSQL on port ${PG_PORT}..."
    "${PG_BIN_PATH}/pg_ctl" -D "${PGDATA}" stop -m fast
    echo "[INFO] PostgreSQL stopped."
else
    echo "[INFO] PostgreSQL is not running."
fi

echo "[SUCCESS] Lab shutdown complete. All services stopped."
SHUTEOF

chmod +x "${SHUTDOWN_SCRIPT}"
echo "[INFO] Shutdown script generated: ${SHUTDOWN_SCRIPT}"
