#!/usr/bin/env bash
# @description: Generates the lab entry point script (lab_entry.sh).
#              Produces Airflow-aware variant if Airflow is provisioned.
#              Sourced by 98_assemble_lab.sh — inherits all variables.
# @generator: generate_lab_entry.sh
# @author: [Nishchay Dubey/iota-sama]

set -euo pipefail

# -----------------------------------------------------------------------------
# 1. ENVIRONMENT VALIDATION
# -----------------------------------------------------------------------------
: "${LAB_HOME:?LAB_HOME is not set. Run via 98_assemble_lab.sh}"
: "${SECRET_FILE:?SECRET_FILE is not set.}"
: "${STACK_ID:?STACK_ID is not set.}"
: "${ENV_NAME:?ENV_NAME is not set.}"

# PostgreSQL variables
: "${PG_PORT:?PG_PORT is not set.}"
: "${PG_LAB_USER:?PG_LAB_USER is not set.}"
: "${PG_LAB_DB:?PG_LAB_DB is not set.}"
: "${PGDATA:?PGDATA is not set.}"
: "${PG_BIN_PATH:?PG_BIN_PATH is not set.}"
: "${PG_LOG_DIR:?PG_LOG_DIR is not set.}"

# Airflow variables
: "${AIRFLOW_PORT:?AIRFLOW_PORT is not set.}"
: "${AIRFLOW_VENV:?AIRFLOW_VENV is not set.}"
: "${AIRFLOW_HOME:?AIRFLOW_HOME is not set.}"
: "${AIRFLOW_CFG:?AIRFLOW_CFG is not set.}"
: "${AIRFLOW_DAGS_FOLDER:?AIRFLOW_DAGS_FOLDER is not set.}"
: "${AIRFLOW_LOG_DIR:?AIRFLOW_LOG_DIR is not set.}"
: "${AIRFLOW_RUN_DIR:?AIRFLOW_RUN_DIR is not set.}"
: "${AIRFLOW_DB_USER:?AIRFLOW_DB_USER is not set.}"
: "${AIRFLOW_DB_NAME:?AIRFLOW_DB_NAME is not set.}"
: "${AIRFLOW_POSTGRES_CONN_ID:?AIRFLOW_POSTGRES_CONN_ID is not set.}"


: "${ENTRY_SCRIPT:="${LAB_HOME}/bin/lab_entry.sh"}"

# -----------------------------------------------------------------------------
# 2. GENERATE LAB ENTRY POINT
# -----------------------------------------------------------------------------
cat > "${ENTRY_SCRIPT}" <<'ENTRYEOF'
#!/usr/bin/env bash
# ==========================================================
# LAB ENTRY POINT — Generated by bootstrap-de-stack
# ==========================================================
# Source this file to load all environment variables AND
# start lab services:
#   source bin/lab_entry.sh
#
# Or run directly to start services and see a summary:
#   <LAB_HOME>/bin/lab_entry.sh
# ==========================================================

LAB_HOME="$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")" 

# Load internal state
if [[ -f "${LAB_HOME}/configs/state.env" ]]; then
    source "${LAB_HOME}/configs/state.env"
else
    echo "[ERROR] State file not found: ${LAB_HOME}/configs/state.env"
    return 1 2>/dev/null || exit 1
fi

# Load secrets
if [[ -f "${SECRET_FILE}" ]]; then
    source "${SECRET_FILE}"
else
    echo "[ERROR] Secrets file not found: ${SECRET_FILE}"
    return 1 2>/dev/null || exit 1
fi

# Load user config (optional)
if [[ -f "${LAB_HOME}/configs/lab_config.sh" ]]; then
    source "${LAB_HOME}/configs/lab_config.sh"
fi

# Start PostgreSQL if not already running
if "${PG_BIN_PATH}/pg_isready" -p "${PG_PORT}" -h localhost >/dev/null 2>&1; then
    echo "[INFO] PostgreSQL is already running on port ${PG_PORT}."
else
    echo "[INFO] Starting PostgreSQL..."
    "${PG_BIN_PATH}/pg_ctl" -D "${PGDATA}" -l "${PG_LOG_DIR}/startup.log" start
    echo "[INFO] PostgreSQL started on port ${PG_PORT}."
fi

# Start Airflow
export AIRFLOW_HOME="${AIRFLOW_HOME}"
export AIRFLOW__DATABASE__SQL_ALCHEMY_CONN="postgresql://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASS}@localhost:${PG_PORT}/${AIRFLOW_DB_NAME}"
export AIRFLOW__API__PORT="${AIRFLOW_PORT}"

# Start scheduler if not running
if [[ -f "${AIRFLOW_RUN_DIR}/airflow-scheduler.pid" ]]; then
    SCHED_PID=$(cat "${AIRFLOW_RUN_DIR}/airflow-scheduler.pid")
    if kill -0 "${SCHED_PID}" 2>/dev/null; then
        echo "[INFO] Airflow scheduler is already running (PID: ${SCHED_PID})."
    else
        echo "[INFO] Starting Airflow scheduler..."
        "${AIRFLOW_VENV}/bin/airflow" scheduler --pid "${AIRFLOW_RUN_DIR}/airflow-scheduler.pid" -D
    fi
else
    echo "[INFO] Starting Airflow scheduler..."
    "${AIRFLOW_VENV}/bin/airflow" scheduler --pid "${AIRFLOW_RUN_DIR}/airflow-scheduler.pid" -D
fi

# Start API server if not running
if [[ -f "${AIRFLOW_RUN_DIR}/airflow-api-server.pid" ]]; then
    API_PID=$(cat "${AIRFLOW_RUN_DIR}/airflow-api-server.pid")
    if kill -0 "${API_PID}" 2>/dev/null; then
        echo "[INFO] Airflow API server is already running (PID: ${API_PID})."
    else
        echo "[INFO] Starting Airflow API server..."
        "${AIRFLOW_VENV}/bin/airflow" api-server --port "${AIRFLOW_PORT}" --pid "${AIRFLOW_RUN_DIR}/airflow-api-server.pid" -D
    fi
else
    echo "[INFO] Starting Airflow API server..."
    "${AIRFLOW_VENV}/bin/airflow" api-server --port "${AIRFLOW_PORT}" --pid "${AIRFLOW_RUN_DIR}/airflow-api-server.pid" -D
fi

# Print summary
echo "=================================================="
echo "  DE Lab Environment: ${ENV_NAME}"
echo "  Lab ID: ${STACK_ID}"
echo "=================================================="
echo ""
echo "  PostgreSQL:"
echo "    Port:     ${PG_PORT}"
echo "    Database: ${PG_LAB_DB}"
echo "    User:     ${PG_LAB_USER}"
echo "    Connect:  psql -h localhost -p ${PG_PORT} -d ${PG_LAB_DB} -U ${PG_LAB_USER}"
echo "    URL:      postgresql://${PG_LAB_USER}@localhost:${PG_PORT}/${PG_LAB_DB}"
echo ""
echo "  Airflow:"
echo "    API Server: http://localhost:${AIRFLOW_PORT}"
echo "    DAGs:       ${AIRFLOW_DAGS_FOLDER}"
echo "    Logs:       ${AIRFLOW_LOG_DIR}"
echo "    Config:     ${AIRFLOW_CFG}"
echo "    Connection: ${AIRFLOW_POSTGRES_CONN_ID} → ${PG_LAB_DB} (user: ${PG_LAB_USER})"
echo ""
echo "  GUI Tool:  DBeaver (https://dbeaver.io)"
echo "             Host: localhost | Port: ${PG_PORT} | Database: ${PG_LAB_DB}"
echo "             Username: ${PG_LAB_USER} | Password: see ${SECRET_FILE}"
echo ""
echo "  Secrets:   ${SECRET_FILE}"
echo "  Config:    ${LAB_HOME}/configs/lab_config.sh"
echo "  Shutdown:  bash ${LAB_HOME}/bin/lab_shutdown.sh"
echo "=================================================="
ENTRYEOF


chmod +x "${ENTRY_SCRIPT}"
echo "[INFO] Entry point generated: ${ENTRY_SCRIPT}"
