#!/usr/bin/env bash
set -euo pipefail

# @description: OS provisioning, directory hierarchies, and secure secrets initialization.
# @script: 00_base_setup.sh
# @author: [Nishchay Dubey/iota-sama]


# Ensure sudo is available
if ! sudo -n true 2>/dev/null; then
    echo "[ERROR] This script (00_base_setup.sh) requires sudo privileges to install system binaries."
    echo "Please run this script via run_setup.sh or run 'sudo -v' before executing it directly."
    exit 1
fi

export DEBIAN_FRONTEND=noninteractive

# Install or Update needed tools
sudo apt update
sudo apt install -y \
  ca-certificates curl wget gnupg lsb-release software-properties-common \
  git build-essential unzip jq \
  python3 python3-venv python3-pip \
  default-jdk uuid-runtime


# Create idempotent and absolute directory hierarchy
PARENT_DIR="$(dirname "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")")"
: "${LAB_HOME:="${PARENT_DIR}/de_lab_testing"}"
export LAB_HOME
mkdir -p "$LAB_HOME"/{bin,configs,data,logs,run,venvs,secrets}


# Define the path for the DE Platform .gitignore
PLATFORM_GITIGNORE="${LAB_HOME}/.gitignore"

if [[ ! -f "$PLATFORM_GITIGNORE" ]]; then
  cat > "$PLATFORM_GITIGNORE" << 'EOF'
# Auto-generated git protection by Bootstrap Script 00_base_setup.sh
data/
logs/
run/
secrets/
venvs/
*.env
EOF
  echo "[INFO] Created .gitignore in platform folder."
else
  echo "[INFO] .gitignore already exists in platform folder. Skipping."
fi


ENV_NAME="${ENV_NAME:-"unnamed_env"}"
STACK_ID=$(uuidgen 2>/dev/null || echo "env-$(date +%s)")

# Generate DE Platform Secrets File with Strict Permissions
: "${SECRET_FILE:="${LAB_HOME}/secrets/generated.env"}"
if [[ ! -f "$SECRET_FILE" ]]; then
  umask 077
  cat > "$SECRET_FILE" <<EOF
# ==========================================================
# SYSTEM-GENERATED SECRETS (Do Not Edit Manually)
# ==========================================================
# This file was automatically generated by 00_base_setup.sh.
# It contains internal credentials and system-state variables
# required for the de_stack_vm platform to function.
#
# SECURITY NOTE:
# This file is protected by 'umask 077' and is visible ONLY
# to the user who ran the setup. It is ignored by Git.
# ==========================================================

# Birth Certificate/System generated identifier of the DE Platform Environment
GEN_DATE=$(date +"%Y-%m-%d-%H:%M:%S-%Z")
ENV_NAME=$ENV_NAME
STACK_ID=$STACK_ID
EOF
fi

export STACK_ID ENV_NAME

echo "Base setup done."
echo "LAB_HOME=$LAB_HOME"