# @description: OS provisioning, Idempotent and absolute directory hierarchies, and secure identity/secrets initialization.
# @author: [Nishchay Dubey/iota-sama]
# @version: 0.1.0-alpha


#!/usr/bin/env bash
set -euo pipefail

export DEBIAN_FRONTEND=noninteractive

# Install or Update needed tools
sudo apt update
sudo apt install -y \
  ca-certificates curl wget gnupg lsb-release software-properties-common \
  git build-essential unzip jq \
  python3 python3-venv python3-pip \
  default-jdk uuid-runtime


# Create idempotent and absolute directory hierarchy
PARENT_DIR="$(dirname "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")")"
STACK_HOME="${STACK_HOME:-"${PARENT_DIR}/de_stack_vm"}"
mkdir -p "$STACK_HOME"/{bin,configs,data,logs,venvs,secrets}


# Define the path for the DE Platform .gitignore
PLATFORM_GITIGNORE="${STACK_HOME}/.gitignore"

if [[ ! -f "$PLATFORM_GITIGNORE" ]]; then
  cat > "$PLATFORM_GITIGNORE" << 'EOF'
# Auto-generated git protection by Bootstrap Script 00_base_setup.sh
data/
logs/
secrets/
venvs/
*.env
EOF
  echo "[INFO] Created .gitignore in platform folder."
else
  echo "[INFO] .gitignore already exists in platform folder. Skipping."
fi


# Generate DE Platform Secrets File with Strict Permissions
SECRET_FILE="$STACK_HOME/secrets/generated.env"
if [[ ! -f "$SECRET_FILE" ]]; then
  umask 077
  cat > "$SECRET_FILE" <<EOF
# ==========================================================
# SYSTEM-GENERATED SECRETS (Do Not Edit Manually)
# ==========================================================
# This file was automatically generated by 00_base_setup.sh.
# It contains internal credentials and system-state variables
# required for the de_stack_vm platform to function.
#
# SECURITY NOTE:
# This file is protected by 'umask 077' and is visible ONLY
# to the user who ran the setup. It is ignored by Git.
# ==========================================================

# Birth Certificate/System generated identifier of the DE Platform Environment
GEN_DATE=$(date)
STACK_ID=$(uuidgen 2>/dev/null || echo "env-$(date +%s)")
ENV_TAG="${ENV_NAME:-"unnamed_env"}"
EOF
fi

echo "Base setup done."
echo "STACK_HOME=$STACK_HOME"
