#!/usr/bin/env bash
set -euo pipefail

# @description: Schema provisioning for PostgreSQL Data Lab.
# @script: 03_provision_pg_schema.sh
# @author: [Nishchay Dubey/iota-sama]

# -----------------------------------------------------------------------------
# 1. PRIVILEGE CHECK
# -----------------------------------------------------------------------------
if ! sudo -n true 2>/dev/null; then
    echo "[ERROR] This script requires sudo privileges for PostgreSQL admin operations."
    echo "Please run via run_setup.sh or run 'sudo -v' before executing directly."
    exit 1
fi

# -----------------------------------------------------------------------------
# 2. ENVIRONMENT VALIDATION
# -----------------------------------------------------------------------------
: "${LAB_HOME:?LAB_HOME is not set. Run base setup first.}"
: "${PGDATA:?PGDATA is not set. Ensure 01_setup_pg_engine.sh ran.}"
: "${PG_BIN_PATH:?PG_BIN_PATH is not set. Ensure 01_setup_pg_engine.sh ran.}"
: "${PG_PORT:?PG_PORT is not set. Ensure 02_runtime_pg_service.sh ran.}"
: "${STACK_ID:?STACK_ID is not set. Ensure 00_base_setup.sh ran.}"
: "${ENV_NAME:?ENV_NAME is not set. Check settings.env.}"
: "${PG_RUNTIME_DIR:?PG_RUNTIME_DIR is not set. Ensure 02_runtime_pg_service.sh ran.}"

SECRET_FILE="${LAB_HOME}/secrets/generated.env"

if [[ ! -f "${SECRET_FILE}" ]]; then
    echo "[ERROR] Secrets file not found: ${SECRET_FILE}"
    echo "Ensure 00_base_setup.sh has been run."
    exit 1
fi

source "${SECRET_FILE}"

# -----------------------------------------------------------------------------
# 3. CREDENTIAL GENERATION (Idempotent)
# -----------------------------------------------------------------------------

#  User name prefix (overridable via settings.env), factory appends unique suffix for isolation
: "${PG_LAB_USER_PREFIX:="lab_admin"}"

if ! grep -q "PG_LAB_PASS" "${SECRET_FILE}"; then
    echo "[INFO] Generating secure DB credentials..."
    PG_LAB_PASS=$(openssl rand -base64 12)
    PG_LAB_USER="${PG_LAB_USER_PREFIX}_${STACK_ID:0:8}"
    PG_LAB_DB="dev_lab"

    cat >> "${SECRET_FILE}" <<EOF

# PostgreSQL Lab Credentials (Generated by 03_provision_pg_schema.sh)
PG_LAB_USER='${PG_LAB_USER}'
PG_LAB_PASS='${PG_LAB_PASS}'
PG_LAB_DB='${PG_LAB_DB}'
EOF

    # Reload to get the new variables
    source "${SECRET_FILE}"
    echo "[SUCCESS] Credentials generated and stored."
else
    echo "[INFO] DB credentials already exist. Using existing values."
fi

# Final validation: ensure all credential variables are set
: "${PG_LAB_USER:?PG_LAB_USER is missing from secrets file.}"
: "${PG_LAB_PASS:?PG_LAB_PASS is missing from secrets file.}"
: "${PG_LAB_DB:=dev_lab}"

# Escape single quotes in password for SQL safety
PG_LAB_PASS_SAFE="${PG_LAB_PASS//\'/\'\'}"

# -----------------------------------------------------------------------------
# 4. ROLE & DATABASE PROVISIONING
# -----------------------------------------------------------------------------
echo "[INFO] Creating role and database (if not exists)..."

"${PG_BIN_PATH}/psql" -h "${PG_RUNTIME_DIR}" -p "${PG_PORT}" -d postgres -t <<EOF
-- Create the Admin Role
DO \$\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${PG_LAB_USER}') THEN
        CREATE ROLE ${PG_LAB_USER} WITH LOGIN PASSWORD '${PG_LAB_PASS_SAFE}';
        RAISE NOTICE 'Role created: %', '${PG_LAB_USER}';
    ELSE
        RAISE NOTICE 'Role already exists: %', '${PG_LAB_USER}';
    END IF;
END
\$\$;

-- Create the Database using the pattern from your draft
SELECT 'CREATE DATABASE ${PG_LAB_DB} OWNER ${PG_LAB_USER}'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${PG_LAB_DB}')
\gexec
EOF

echo "[SUCCESS] Role and database provisioned."

# -----------------------------------------------------------------------------
# 5. MEDALLION SCHEMA INITIALIZATION
# -----------------------------------------------------------------------------
echo "[INFO] Initializing Medallion Architecture schemas..."

SCHEMAS=("raw" "staging" "analytics")

for schema in "${SCHEMAS[@]}"; do
    "${PG_BIN_PATH}/psql" -h "${PG_RUNTIME_DIR}" -p "${PG_PORT}" -d "${PG_LAB_DB}" -t \
        -c "CREATE SCHEMA IF NOT EXISTS ${schema} AUTHORIZATION ${PG_LAB_USER};"
    echo "  [OK] Schema: ${schema}"
done

echo "[SUCCESS] Medallion schemas initialized."

# -----------------------------------------------------------------------------
# 6. SUMMARY
# -----------------------------------------------------------------------------
echo "======================================================="
echo "[SUCCESS] Data Lab '${PG_LAB_DB}' is ready."
echo ""
echo "  Database: ${PG_LAB_DB}"
echo "  User:     ${PG_LAB_USER}"
echo "  Password: (stored in ${SECRET_FILE})"
echo "  Port:     ${PG_PORT}"
echo "  Schemas:  ${SCHEMAS[*]}"
echo ""
echo "  Connect:  psql -h localhost -p ${PG_PORT} -d ${PG_LAB_DB} -U ${PG_LAB_USER}"
echo "======================================================="