#!/usr/bin/env bash
set -euo pipefail

# @description: Create Airflow's PostgreSQL role, database, and initialize the metadata schema.
# @script: 05_provision_airflow_db.sh
# @author: [Nishchay Dubey/iota-sama]

# -----------------------------------------------------------------------------
# 1. PRIVILEGE CHECK (Fail-Fast)
# -----------------------------------------------------------------------------
if ! sudo -n true 2>/dev/null; then
    echo "[ERROR] This script requires sudo privileges for PostgreSQL admin operations."
    echo "Please run via run_setup.sh or run 'sudo -v' before executing directly."
    exit 1
fi

# -----------------------------------------------------------------------------
# 2. ENVIRONMENT VALIDATION
# -----------------------------------------------------------------------------
: "${LAB_HOME:?LAB_HOME is not set. Run base setup first.}"
: "${PGDATA:?PGDATA is not set. Ensure 01_setup_pg_engine.sh ran.}"
: "${PG_BIN_PATH:?PG_BIN_PATH is not set. Ensure 01_setup_pg_engine.sh ran.}"
: "${PG_PORT:?PG_PORT is not set. Ensure 02_runtime_pg_service.sh ran.}"
: "${PG_RUNTIME_DIR:?PG_RUNTIME_DIR is not set. Ensure 02_runtime_pg_service.sh ran.}"
: "${STACK_ID:?STACK_ID is not set. Ensure 00_base_setup.sh ran.}"
: "${ENV_NAME:?ENV_NAME is not set. Check settings.env.}"
: "${AIRFLOW_VENV:?AIRFLOW_VENV is not set. Ensure 04_setup_airflow_venv.sh ran.}"
: "${AIRFLOW_HOME:?AIRFLOW_HOME is not set. Ensure 04_setup_airflow_venv.sh ran.}"

SECRET_FILE="${LAB_HOME}/secrets/generated.env"

if [[ ! -f "${SECRET_FILE}" ]]; then
    echo "[ERROR] Secrets file not found: ${SECRET_FILE}"
    echo "Ensure 00_base_setup.sh and 03_provision_pg_schema.sh have been run."
    exit 1
fi

source "${SECRET_FILE}"

# -----------------------------------------------------------------------------
# 3. DEFAULTS
# -----------------------------------------------------------------------------
: "${AIRFLOW_DB_NAME:="airflow_db"}"
: "${AIRFLOW_DB_USER_PREFIX:="airflow_admin"}"
: "${AIRFLOW_DB_USER:="${AIRFLOW_DB_USER_PREFIX}_${STACK_ID:0:8}"}"

# -----------------------------------------------------------------------------
# 4. GENERATE AIRFLOW DB PASSWORD (Idempotent)
# -----------------------------------------------------------------------------
if ! grep -q "AIRFLOW_DB_PASS" "${SECRET_FILE}"; then
    echo "[INFO] Generating Airflow database credentials..."
    AIRFLOW_DB_PASS=$(openssl rand -base64 12)

    cat >> "${SECRET_FILE}" <<EOF

# Airflow Metadata Database Credentials (Generated by 05_provision_airflow_db.sh)
AIRFLOW_DB_USER='${AIRFLOW_DB_USER}'
AIRFLOW_DB_PASS='${AIRFLOW_DB_PASS}'
AIRFLOW_DB_NAME='${AIRFLOW_DB_NAME}'
EOF

    source "${SECRET_FILE}"
    echo "[SUCCESS] Airflow database credentials generated and stored."
else
    # Validation
    : "${AIRFLOW_DB_USER:?AIRFLOW_DB_USER is missing from secrets file.}"
    : "${AIRFLOW_DB_PASS:?AIRFLOW_DB_PASS is missing from secrets file.}"
    : "${AIRFLOW_DB_NAME:?AIRFLOW_DB_NAME is missing from secrets file.}"
    
    echo "[INFO] Airflow DB credentials already exist. Using existing values."
fi


# Escape single quotes for SQL safety
AIRFLOW_DB_PASS_SAFE="${AIRFLOW_DB_PASS//\'/\'\'}"


# -----------------------------------------------------------------------------
# 5. CREATE AIRFLOW ROLE (Idempotent)
# -----------------------------------------------------------------------------
echo "[INFO] Creating Airflow database role '${AIRFLOW_DB_USER}'..."

"${PG_BIN_PATH}/psql" -h "${PG_RUNTIME_DIR}" -p "${PG_PORT}" -d postgres -t <<EOF
DO \$\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${AIRFLOW_DB_USER}') THEN
        CREATE ROLE ${AIRFLOW_DB_USER} WITH LOGIN PASSWORD '${AIRFLOW_DB_PASS_SAFE}';
        RAISE NOTICE 'Role created: %', '${AIRFLOW_DB_USER}';
    ELSE
        RAISE NOTICE 'Role already exists: %', '${AIRFLOW_DB_USER}';
    END IF;
END
\$\$;
EOF

echo "[SUCCESS] Airflow role provisioned."


# -----------------------------------------------------------------------------
# 6. CREATE AIRFLOW DATABASE (Idempotent)
# -----------------------------------------------------------------------------
echo "[INFO] Creating Airflow metadata database '${AIRFLOW_DB_NAME}'..."

"${PG_BIN_PATH}/psql" -h "${PG_RUNTIME_DIR}" -p "${PG_PORT}" -d postgres -t <<EOF
SELECT 'CREATE DATABASE ${AIRFLOW_DB_NAME} OWNER ${AIRFLOW_DB_USER}'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${AIRFLOW_DB_NAME}')
\gexec
EOF

echo "[SUCCESS] Airflow database created."

# Grant ALL (Schema, Connect) on database to airflow user for migration
"${PG_BIN_PATH}/psql" -h "${PG_RUNTIME_DIR}" -p "${PG_PORT}" -d postgres -t <<EOF
GRANT ALL PRIVILEGES ON DATABASE ${AIRFLOW_DB_NAME} TO ${AIRFLOW_DB_USER};
EOF

# The auto created public schema is still owned by the superuser, not by the database owner.
# Grant full control to the Airflow user so db migrate can create/manage tables.
"${PG_BIN_PATH}/psql" -h "${PG_RUNTIME_DIR}" -p "${PG_PORT}" -d "${AIRFLOW_DB_NAME}" -t <<EOF
GRANT ALL ON SCHEMA public TO ${AIRFLOW_DB_USER};
EOF

# -----------------------------------------------------------------------------
# 7. INITIALIZE AIRFLOW METADATA SCHEMA (Idempotent)
# -----------------------------------------------------------------------------
echo "[INFO] Initializing Airflow metadata schema..."

# Build the SQLAlchemy connection string
AIRFLOW_DB_CONN="postgresql://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASS}@localhost:${PG_PORT}/${AIRFLOW_DB_NAME}"
export AIRFLOW__DATABASE__SQL_ALCHEMY_CONN="${AIRFLOW_DB_CONN}"

# Run airflow db migrate (creates tables if they don't exist)
if "${AIRFLOW_VENV}/bin/airflow" db migrate 2>&1; then
    echo "[SUCCESS] Airflow metadata schema initialized (or already up to date)."
else
    echo "[ERROR] Airflow db migrate failed."
    echo "Connection string used: postgresql://${AIRFLOW_DB_USER}:****@localhost:${PG_PORT}/${AIRFLOW_DB_NAME}"
    exit 1
fi


# -----------------------------------------------------------------------------
# 8. EXPORT FOR DOWNSTREAM SCRIPTS
# -----------------------------------------------------------------------------
export AIRFLOW_DB_USER
export AIRFLOW_DB_PASS
export AIRFLOW_DB_NAME
export AIRFLOW_DB_CONN

echo "[SUCCESS] Script 05: Airflow metadata database is ready."
echo "  Database: ${AIRFLOW_DB_NAME}"
echo "  User:     ${AIRFLOW_DB_USER}"
echo "  Password: (stored in ${SECRET_FILE})"