#!/usr/bin/env bash
set -euo pipefail

# @description: Generate airflow.cfg, Fernet key, and seed essential connections.
# @script: 06_configure_airflow.sh
# @author: [Nishchay Dubey/iota-sama]

# -----------------------------------------------------------------------------
# 1. ENVIRONMENT VALIDATION
# -----------------------------------------------------------------------------
: "${LAB_HOME:?LAB_HOME is not set. Run base setup first.}"
: "${AIRFLOW_VENV:?AIRFLOW_VENV is not set. Ensure 04_setup_airflow_venv.sh ran.}"
: "${AIRFLOW_HOME:?AIRFLOW_HOME is not set. Ensure 04_setup_airflow_venv.sh ran.}"
: "${AIRFLOW_DB_USER:?AIRFLOW_DB_USER is not set. Ensure 05_provision_airflow_db.sh ran.}"
: "${AIRFLOW_DB_PASS:?AIRFLOW_DB_PASS is not set. Ensure 05_provision_airflow_db.sh ran.}"
: "${AIRFLOW_DB_NAME:?AIRFLOW_DB_NAME is not set. Ensure 05_provision_airflow_db.sh ran.}"
: "${PG_PORT:?PG_PORT is not set. Ensure 02_runtime_pg_service.sh ran.}"
: "${PG_LAB_USER:?PG_LAB_USER is not set. Ensure 03_provision_pg_schema.sh ran.}"
: "${PG_LAB_PASS:?PG_LAB_PASS is not set. Ensure 03_provision_pg_schema.sh ran.}"
: "${PG_LAB_DB:?PG_LAB_DB is not set. Ensure 03_provision_pg_schema.sh ran.}"

: "${SECRET_FILE:="${LAB_HOME}/secrets/generated.env"}"
: "${AIRFLOW_CFG:="${AIRFLOW_HOME}/airflow.cfg"}"

# -----------------------------------------------------------------------------
# 2. DEFAULTS
# -----------------------------------------------------------------------------
: "${AIRFLOW_EXECUTOR:="LocalExecutor"}"
: "${AIRFLOW_DAGS_FOLDER:="${LAB_HOME}/data/airflow/dags"}"
: "${AIRFLOW_LOAD_EXAMPLES:="false"}"
: "${AIRFLOW__API__EXPOSE_CONFIG:="false"}"  

# Load secrets if not already sourced
if [[ -z "${PG_LAB_PASS:-}" ]]; then
    source "${SECRET_FILE}"
fi

# -----------------------------------------------------------------------------
# 3. GENERATE FERNET KEY (Idempotent)
# -----------------------------------------------------------------------------
echo "[INFO] Managing Fernet key for connection encryption..."

if ! grep -q "AIRFLOW_FERNET_KEY" "${SECRET_FILE}"; then
    echo "[INFO] Generating new Fernet key..."
    AIRFLOW_FERNET_KEY=$(python3 -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())")
    
    cat >> "${SECRET_FILE}" <<EOF

# Airflow Fernet Key (Generated by 06_configure_airflow.sh)
# Used to encrypt connection passwords and variables at rest.
# Losing this key means losing all stored connections and variables.
AIRFLOW_FERNET_KEY='${AIRFLOW_FERNET_KEY}'
EOF

    source "${SECRET_FILE}"
    echo "[SUCCESS] Fernet key generated and stored."
else
    echo "[INFO] Fernet key already exists. Using existing key."
    source "${SECRET_FILE}"
fi

: "${AIRFLOW_FERNET_KEY:?AIRFLOW_FERNET_KEY must be set.}"

# -----------------------------------------------------------------------------
# 4. CREATE DIRECTORY STRUCTURE
# -----------------------------------------------------------------------------
echo "[INFO] Creating Airflow directory structure..."
mkdir -p "${AIRFLOW_DAGS_FOLDER}"
mkdir -p "${LAB_HOME}/logs/airflow"
mkdir -p "${LAB_HOME}/run/airflow"
mkdir -p "${LAB_HOME}/data/airflow/plugins"

# -----------------------------------------------------------------------------
# 5. GENERATE AIRFLOW.CFG (Idempotent via check)
# -----------------------------------------------------------------------------
if [[ -f "${AIRFLOW_CFG}" ]]; then
    echo "[INFO] airflow.cfg already exists. Skipping generation."
else
    echo "[INFO] Generating airflow.cfg..."
    
    cat > "${AIRFLOW_CFG}" <<EOF
# ==========================================================
# Airflow Configuration — Generated by bootstrap-de-stack
# Script: 06_configure_airflow.sh
# Lab: ${ENV_NAME} (${STACK_ID})
# ==========================================================
# User customizations should be done through the Airflow UI,
# environment variables, or by editing this file manually.
# ==========================================================

[core]
# The home folder for Airflow
airflow_home = ${AIRFLOW_HOME}

# The folder where DAG files are stored
dags_folder = ${AIRFLOW_DAGS_FOLDER}

# The executor class
executor = ${AIRFLOW_EXECUTOR}

# SQLAlchemy connection string for the metadata database
sql_alchemy_conn = postgresql://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASS}@localhost:${PG_PORT}/${AIRFLOW_DB_NAME}

# Load example DAGs
load_examples = ${AIRFLOW_LOAD_EXAMPLES}

# Default timezone
default_timezone = UTC

# Fernet key for encrypting connections and variables
fernet_key = ${AIRFLOW_FERNET_KEY}

# Executor-specific: parallelism for LocalExecutor
parallelism = 32

# Maximum number of active DAG runs per DAG
max_active_runs_per_dag = 16

[database]
# The SQLAlchemy connection string
sql_alchemy_conn = postgresql://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASS}@localhost:${PG_PORT}/${AIRFLOW_DB_NAME}

# Database connection pooling
sql_alchemy_pool_size = 5
sql_alchemy_pool_recycle = 3600

[api]
# Port is set via environment variable or runtime overrides
# to support per-lab port discovery. Do not hardcode here.

# The base URL of the API server
base_url = http://localhost:8080

# Expose Airflow configuration in UI
expose_config = ${AIRFLOW__API__EXPOSE_CONFIG}

# API server UI settings
default_ui_timezone = UTC

[logging]
# Log storage location
base_log_folder = ${LAB_HOME}/logs/airflow

# Log level
logging_level = INFO

[scheduler]
# Scheduler settings
min_file_process_interval = 30
dag_dir_list_interval = 30

[api]
# Enable the REST API
enable_experimental_api = True
EOF

    echo "[SUCCESS] airflow.cfg generated at ${AIRFLOW_CFG}"
fi

# -----------------------------------------------------------------------------
# 6. SEED POSTGRESQL CONNECTION (Idempotent)
# -----------------------------------------------------------------------------
echo "[INFO] Seeding Airflow connections..."

# Set/Update DB connection for CLI operations 
: "${AIRFLOW_POSTGRES_CONN_ID:="lab_postgres"}"
export AIRFLOW_POSTGRES_CONN_ID
export AIRFLOW__DATABASE__SQL_ALCHEMY_CONN="postgresql://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASS}@localhost:${PG_PORT}/${AIRFLOW_DB_NAME}"

# Seed AIRFLOW_POSTGRES_CONN_ID connection for user DAGs
POSTGRES_CONN_URI="postgresql://${PG_LAB_USER}:${PG_LAB_PASS}@localhost:${PG_PORT}/${PG_LAB_DB}"

if "${AIRFLOW_VENV}/bin/airflow" connections list 2>/dev/null | grep -q "${AIRFLOW_POSTGRES_CONN_ID}"; then
    echo "[INFO] Connection '${AIRFLOW_POSTGRES_CONN_ID}' already exists. Updating..."
    "${AIRFLOW_VENV}/bin/airflow" connections delete "${AIRFLOW_POSTGRES_CONN_ID}" 2>/dev/null || true
fi

"${AIRFLOW_VENV}/bin/airflow" connections add "${AIRFLOW_POSTGRES_CONN_ID}" \
    --conn-type "postgres" \
    --conn-host "localhost" \
    --conn-port "${PG_PORT}" \
    --conn-login "${PG_LAB_USER}" \
    --conn-password "${PG_LAB_PASS}" \
    --conn-schema "${PG_LAB_DB}" \
    --conn-extra '{"sslmode": "disable"}'

echo "[SUCCESS] Connection '${AIRFLOW_POSTGRES_CONN_ID}' seeded."

# -----------------------------------------------------------------------------
# 7. EXPORT FOR DOWNSTREAM SCRIPTS
# -----------------------------------------------------------------------------
export AIRFLOW_CFG
export AIRFLOW_DAGS_FOLDER

echo "[SUCCESS] Script 06: Airflow configuration is complete."
echo "  Config:       ${AIRFLOW_CFG}"
echo "  DAGs folder:  ${AIRFLOW_DAGS_FOLDER}"
echo "  Executor:     ${AIRFLOW_EXECUTOR}"
echo "  Connection:   ${AIRFLOW_POSTGRES_CONN_ID} → ${PG_LAB_DB} (user: ${PG_LAB_USER})"
