#!/usr/bin/env bash
set -euo pipefail

# @description: Generates the Lab Entry Point and State Manifest.
# @script: 99_generate_lab_manifest.sh
# @author: [Nishchay Dubey/iota-sama]

# -----------------------------------------------------------------------------
# 1. ENVIRONMENT VALIDATION
# -----------------------------------------------------------------------------
: "${LAB_HOME:?LAB_HOME is not set. Run base setup first.}"
: "${STACK_ID:?STACK_ID is not set.}"
: "${ENV_NAME:?ENV_NAME is not set.}"
: "${PG_VERSION:?PG_VERSION is not set.}"
: "${PGDATA:?PGDATA is not set.}"
: "${PG_BIN_PATH:?PG_BIN_PATH is not set.}"
: "${PG_PORT:?PG_PORT is not set.}"
: "${PG_LAB_USER:?PG_LAB_USER is not set.}"
: "${PG_LAB_DB:?PG_LAB_DB is not set.}"

SECRET_FILE="${LAB_HOME}/secrets/generated.env"
STATE_FILE="${LAB_HOME}/configs/state.env"
ENTRY_SCRIPT="${LAB_HOME}/bin/lab_entry.sh"
USER_CONFIG="${LAB_HOME}/configs/lab_config.sh"

# -----------------------------------------------------------------------------
# 2. CREATE DIRECTORIES
# -----------------------------------------------------------------------------
mkdir -p "${LAB_HOME}/bin"
mkdir -p "${LAB_HOME}/configs"

# -----------------------------------------------------------------------------
# 3. GENERATE STATE FILE (Internal — DO NOT EDIT)
# -----------------------------------------------------------------------------
cat > "${STATE_FILE}" <<EOF
# ==========================================================
# INTERNAL LAB STATE — Generated by bootstrap-de-stack
# ==========================================================
# DO NOT EDIT THIS FILE.
# This file is regenerated every time the factory runs.
# Use lab_config.sh for custom settings.
# ==========================================================
# Lab Identity
export STACK_ID="${STACK_ID}"
export ENV_NAME="${ENV_NAME}"
export LAB_HOME="${LAB_HOME}"

# PostgreSQL Configuration
export PG_VERSION="${PG_VERSION}"
export PG_PORT="${PG_PORT}"
export PGDATA="${PGDATA}"
export PG_BIN_PATH="${PG_BIN_PATH}"
export PG_RUN_DIR="${PG_RUN_DIR}"
export PG_LOG_DIR="${PG_LOG_DIR}"
export PG_CUSTOM_CONF="${PG_CUSTOM_CONF}"

# Database Access
export PG_LAB_USER="${PG_LAB_USER}"
export PG_LAB_DB="${PG_LAB_DB}"

# Secrets Location
export SECRET_FILE="${SECRET_FILE}"
EOF

echo "[INFO] State file generated: ${STATE_FILE}"

# -----------------------------------------------------------------------------
# 4. GENERATE USER CONFIG FILE (Only if not exists)
# -----------------------------------------------------------------------------
if [[ ! -f "${USER_CONFIG}" ]]; then
    cat > "${USER_CONFIG}" <<EOF
# ==========================================================
# LAB CONFIGURATION — User-Editable Settings
# ==========================================================
# This file is generated once and never overwritten.
# Add your custom environment variables and aliases below.
# ==========================================================
#
# TIP: For PostgreSQL tuning (work_mem, effective_cache_size,
# wal_level, etc.), edit the configuration file directly:
#
#   nano \${PGDATA}/custom_lab.conf
#
# Then restart PostgreSQL:
#
#   \${PG_BIN_PATH}/pg_ctl -D \${PGDATA} restart
#
# All variables (\${PGDATA}, \${PG_BIN_PATH}, \${PG_PORT}, etc.)
# are available after sourcing:
#
#   source \${LAB_HOME}/bin/lab_entry.sh
# ==========================================================
EOF
    echo "[INFO] User config created: ${USER_CONFIG}"
else
    echo "[INFO] User config already exists. Skipping (preserving user edits)."
fi

# -----------------------------------------------------------------------------
# 5. GENERATE LAB ENTRY POINT
# -----------------------------------------------------------------------------
cat > "${ENTRY_SCRIPT}" <<'ENTRY_EOF'
#!/usr/bin/env bash
# ==========================================================
# LAB ENTRY POINT — Generated by bootstrap-de-stack
# ==========================================================
# Source this file to load all environment variables:
#   source bin/lab_entry.sh
#
# Or run directly to see a summary:
#   bash bin/lab_entry.sh
# ==========================================================

LAB_HOME="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Load internal state
if [[ -f "${LAB_HOME}/configs/state.env" ]]; then
    source "${LAB_HOME}/configs/state.env"
else
    echo "[ERROR] State file not found: ${LAB_HOME}/configs/state.env"
    return 1 2>/dev/null || exit 1
fi

# Load secrets
if [[ -f "${SECRET_FILE}" ]]; then
    source "${SECRET_FILE}"
else
    echo "[ERROR] Secrets file not found: ${SECRET_FILE}"
    return 1 2>/dev/null || exit 1
fi

# Load user config (optional)
if [[ -f "${LAB_HOME}/configs/lab_config.sh" ]]; then
    source "${LAB_HOME}/configs/lab_config.sh"
fi

# Print summary
echo "=================================================="
echo "  DE Lab Environment: ${ENV_NAME}"
echo "  Lab ID: ${STACK_ID}"
echo "=================================================="
echo ""
echo "  PostgreSQL:"
echo "    Port:     ${PG_PORT}"
echo "    Database: ${PG_LAB_DB}"
echo "    User:     ${PG_LAB_USER}"
echo "    Connect:  psql -h localhost -p ${PG_PORT} -d ${PG_LAB_DB} -U ${PG_LAB_USER}"
echo "    URL:      postgresql://${PG_LAB_USER}@localhost:${PG_PORT}/${PG_LAB_DB}"
echo ""
echo "  GUI Tool:  DBeaver (https://dbeaver.io)"
echo "             Host: localhost | Port: ${PG_PORT} | Database: ${PG_LAB_DB}"
echo "             Username: ${PG_LAB_USER} | Password: see ${SECRET_FILE}"
echo ""
echo "  Secrets:   ${SECRET_FILE}"
echo "  Config:    ${LAB_HOME}/configs/lab_config.sh"
echo "=================================================="
ENTRY_EOF

chmod +x "${ENTRY_SCRIPT}"

echo "[INFO] Entry point generated: ${ENTRY_SCRIPT}"
echo "[SUCCESS] Lab manifest generation complete."
